version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "testLambda"
s3_bucket = "samtestpackage-testlambda-app"
s3_prefix = "testLambda"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
